# Week 2 Assignment - Pandas Basics

In [27]:
# 1. Import pandas
import pandas as pd

In [28]:
# 2. Read the JSON file
sd = pd.read_json('students_data.json')

In [29]:
# 3. Display first 5 rows
sd.head()

,id,name,age,gender,phone,email,location,district,province,courses_enrolled,fees_paid,fees_due,attendance,marks,batch,join_date,passed,scholarship
0,1,Sabina Pandey,19,Male,9866879003,sabina.pandey1@gmail.com,Dharan,Sunsari,Koshi,"[NodeJS, C++]",17394,1532,60,84,AI Udaan Day,2026-07-26,True,False
1,2,Sujan Poudel,28,Male,9870676580,sujan.poudel2@gmail.com,Nepalgunj,Banke,Lumbini,[Flutter],46200,3006,75,78,Evening,2026-12-02,True,False
2,3,Nabin Pandey,26,Male,9834006426,nabin.pandey3@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Django, Deep Learning, Python, React]",37409,3541,94,59,Weekend,2026-08-06,True,False
3,4,Roshan Regmi,27,Female,9811229824,roshan.regmi4@gmail.com,Dharan,Sunsari,Koshi,"[Figma, Python, Flutter, Excel]",47846,1196,90,73,Weekend,2026-10-20,True,False
4,5,Anisha Regmi,25,Male,9824458163,anisha.regmi5@gmail.com,Chitwan,Chitwan,Bagmati,[Data Science],23403,6333,76,62,Evening,2026-12-20,True,False

In [30]:
# 4. Display last 3 rows
sd.tail(3)

,id,name,age,gender,phone,email,location,district,province,courses_enrolled,fees_paid,fees_due,attendance,marks,batch,join_date,passed,scholarship
497,498,Sabina Khadka,25,Male,9820772678,sabina.khadka498@gmail.com,Janakpur,Dhanusha,Madhesh,"[C++, Digital Marketing, Excel, Power BI]",16298,2316,81,85,Evening,2026-07-15,True,False
498,499,Rohan Acharya,30,Female,9833337211,rohan.acharya499@gmail.com,Chitwan,Chitwan,Bagmati,"[C++, Digital Marketing]",37942,1242,73,65,Evening,2026-01-09,True,False
499,500,Sujan KC,23,Female,9840665873,sujan.kc500@gmail.com,Nepalgunj,Banke,Lumbini,"[Figma, AI/ML]",27145,917,65,98,Morning,2026-12-19,True,False

In [31]:
# 5. Find the shape of dataset
sd.shape

(500, 18)

In [32]:
# 6. Display column names
sd.columns

Index(['id', 'name', 'age', 'gender', 'phone', 'email', 'location', 'district',
       'province', 'courses_enrolled', 'fees_paid', 'fees_due', 'attendance',
       'marks', 'batch', 'join_date', 'passed', 'scholarship'],
      dtype='str')

In [33]:
# 7. Display data types
sd.dtypes

id                   int64
name                   str
age                  int64
gender                 str
phone                int64
email                  str
location               str
district               str
province               str
courses_enrolled    object
fees_paid            int64
fees_due             int64
attendance           int64
marks                int64
batch                  str
join_date              str
passed                bool
scholarship           bool
dtype: object

In [34]:
# 8. Show complete information using info()
sd.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                500 non-null    int64
 1   name              500 non-null    str
 2   age               500 non-null    int64
 3   gender            500 non-null    str
 4   phone             500 non-null    int64
 5   email             500 non-null    str
 6   location          500 non-null    str
 7   district          500 non-null    str
 8   province          500 non-null    str
 9   courses_enrolled  500 non-null    object
 10  fees_paid         500 non-null    int64
 11  fees_due          500 non-null    int64
 12  attendance        500 non-null    int64
 13  marks             500 non-null    int64
 14  batch             500 non-null    str
 15  join_date         500 non-null    str
 16  passed            500 non-null    bool
 17  scholarship       500 non-null    bool
dtypes: bool(2), int64(7), object(1), str(8)
memory usage: 63.6+ KB

In [35]:
# 9. Generate statistical summary using describe()
sd.describe()

,id,age,phone,fees_paid,fees_due,attendance,marks
count,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.000000,500.000000
mean,250.500000,23.746000,9.850151e+09,33232.086000,5137.020000,80.402000,71.670000
std,144.481833,3.932482,2.944077e+07,10109.900089,2947.700174,12.436951,16.250454
min,1.000000,17.000000,9.800039e+09,15148.000000,29.000000,60.000000,45.000000
25%,125.750000,20.000000,9.823999e+09,23946.000000,2458.750000,69.000000,58.000000
50%,250.500000,24.000000,9.851883e+09,34022.500000,5427.500000,81.000000,70.000000
75%,375.250000,27.000000,9.875147e+09,41986.500000,7572.250000,92.000000,86.000000
max,500.000000,30.000000,9.899911e+09,49911.000000,9986.000000,100.000000,99.000000

In [36]:
# 10. Display only Name column
sd['name']

0      Sabina Pandey
1       Sujan Poudel
2       Nabin Pandey
3       Roshan Regmi
4       Anisha Regmi
           ...
495       Asmita Rai
496     Ramesh Joshi
497    Sabina Khadka
498    Rohan Acharya
499         Sujan KC
Name: name, Length: 500, dtype: str

In [37]:
# 11. Display Name and Age
sd[['name', 'age']]

              name  age
0    Sabina Pandey   19
1     Sujan Poudel   28
2     Nabin Pandey   26
3     Roshan Regmi   27
4     Anisha Regmi   25
..             ...  ...
495     Asmita Rai   27
496   Ramesh Joshi   28
497  Sabina Khadka   25
498  Rohan Acharya   30
499       Sujan KC   23

[500 rows x 2 columns]

In [38]:
# 12. Display first student
sd.iloc[0]

id                                         1
name                           Sabina Pandey
age                                       19
gender                                  Male
phone                             9866879003
email               sabina.pandey1@gmail.com
location                              Dharan
district                             Sunsari
province                               Koshi
courses_enrolled               [NodeJS, C++]
fees_paid                              17394
fees_due                                1532
attendance                                60
marks                                     84
batch                           AI Udaan Day
join_date                         2026-07-26
passed                                  True
scholarship                            False
Name: 0, dtype: object

In [39]:
# 13. Display last student
sd.iloc[-1]

id                                    500
name                             Sujan KC
age                                    23
gender                             Female
phone                          9840665873
email               sujan.kc500@gmail.com
location                        Nepalgunj
district                            Banke
province                          Lumbini
courses_enrolled           [Figma, AI/ML]
fees_paid                           27145
fees_due                              917
attendance                             65
marks                                  98
batch                             Morning
join_date                      2026-12-19
passed                               True
scholarship                         False
Name: 499, dtype: object

In [40]:
# 14. Display student with id = 5
sd[sd['id'] == 5]

,id,name,age,gender,phone,email,location,district,province,courses_enrolled,fees_paid,fees_due,attendance,marks,batch,join_date,passed,scholarship
4,5,Anisha Regmi,25,Male,9824458163,anisha.regmi5@gmail.com,Chitwan,Chitwan,Bagmati,[Data Science],23403,6333,76,62,Evening,2026-12-20,True,False

In [41]:
# 15. Display students from Kathmandu
sd[sd['location'] == 'Kathmandu']

,id,name,age,gender,phone,email,location,district,province,courses_enrolled,fees_paid,fees_due,attendance,marks,batch,join_date,passed,scholarship
2,3,Nabin Pandey,26,Male,9834006426,nabin.pandey3@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Django, Deep Learning, Python, React]",37409,3541,94,59,Weekend,2026-08-06,True,False
14,15,Ramesh Dahal,17,Female,9819481915,ramesh.dahal15@gmail.com,Kathmandu,Kathmandu,Bagmati,[UI/UX],31492,6616,82,84,Morning,2026-10-09,True,False
15,16,Suman Adhikari,26,Female,9874774221,suman.adhikari16@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Digital Marketing, Deep Learning, MERN]",47608,7760,87,88,Evening,2026-12-14,True,False
49,50,Suman Gautam,24,Female,9818038621,suman.gautam50@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Deep Learning, Power BI]",46170,7379,60,47,Weekend,2026-09-09,False,False
51,52,Sita Joshi,26,Male,9809412290,sita.joshi52@gmail.com,Kathmandu,Kathmandu,Bagmati,"[MERN, NodeJS, Java]",31410,7869,90,55,AI Udaan Day,2026-11-15,True,False
58,59,Alina Pandey,29,Female,9877806260,alina.pandey59@gmail.com,Kathmandu,Kathmandu,Bagmati,"[MERN, C++]",39318,6861,91,88,AI Udaan Day,2026-02-23,True,False
60,61,Gita Pandey,22,Male,9832380586,gita.pandey61@gmail.com,Kathmandu,Kathmandu,Bagmati,[Django],17430,7768,86,48,Morning,2026-01-03,False,False
80,81,Asmita Magar,28,Male,9804393568,asmita.magar81@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Flutter, Java, NodeJS, React]",21704,40,62,76,AI Udaan Day,2026-05-18,True,False
82,83,Prakash Adhikari,24,Male,9887484710,prakash.adhikari83@gmail.com,Kathmandu,Kathmandu,Bagmati,"[MERN, React, UI/UX, Excel]",37731,1513,92,60,Weekend,2026-06-16,True,False
84,85,Ritika Dahal,17,Female,9893591663,ritika.dahal85@gmail.com,Kathmandu,Kathmandu,Bagmati,"[MERN, NodeJS]",41535,4717,67,64,Weekend,2026-11-02,True,False
102,103,Suman Shrestha,17,Female,9882237253,suman.shrestha103@gmail.com,Kathmandu,Kathmandu,Bagmati,"[React, NodeJS, UI/UX]",45980,3979,66,82,AI Udaan Day,2026-06-03,True,False
104,105,Anisha Karki,27,Female,9885151375,anisha.karki105@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Figma, UI/UX]",36371,9527,81,54,Morning,2026-06-11,True,False
143,144,Ramesh KC,30,Male,9853758736,ramesh.kc144@gmail.com,Kathmandu,Kathmandu,Bagmati,[Flutter],42819,5161,97,65,Morning,2026-12-20,True,False
155,156,Ramesh Lama,25,Female,9804641806,ramesh.lama156@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Data Science, Digital Marketing]",25428,6277,98,87,Morning,2026-11-04,True,False
156,157,Prakash Pandey,17,Male,9836680686,prakash.pandey157@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Flutter, MERN]",49179,650,61,45,Morning,2026-08-07,False,False
157,158,Alina Adhikari,23,Male,9809190897,alina.adhikari158@gmail.com,Kathmandu,Kathmandu,Bagmati,"[C++, Data Science, Power BI, Deep Learning]",47255,9786,73,87,AI Udaan Day,2026-06-26,True,False
162,163,Alina Dahal,22,Female,9815602549,alina.dahal163@gmail.com,Kathmandu,Kathmandu,Bagmati,[Java],23612,3169,96,65,Weekend,2026-04-01,True,False
164,165,Sita Rai,28,Female,9832128800,sita.rai165@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Flutter, Django]",39474,4809,98,87,Morning,2026-04-07,True,False
172,173,Anisha Pandey,24,Male,9867701759,anisha.pandey173@gmail.com,Kathmandu,Kathmandu,Bagmati,"[MERN, Data Science]",33777,5805,85,52,AI Udaan Day,2026-02-09,True,False
173,174,Rohan Karki,28,Male,9862974059,rohan.karki174@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Java, Excel]",19874,1689,71,85,AI Udaan Day,2026-03-10,True,False
192,193,Sita KC,22,Male,9824611134,sita.kc193@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Java, Flutter]",42525,8572,90,76,Evening,2026-07-16,True,False
195,196,Mina Pandey,25,Female,9878164993,mina.pandey196@gmail.com,Kathmandu,Kathmandu,Bagmati,"[React, MERN, Power BI, Excel]",37766,5392,62,62,Evening,2026-08-08,True,False
209,210,Ritika Adhikari,25,Female,9836351743,ritika.adhikari210@gmail.com,Kathmandu,Kathmandu,Bagmati,"[MERN, AI/ML, Digital Marketing, Django]",42816,8463,98,98,AI Udaan Day,2026-09-26,True,True
216,217,Nisha KC,27,Male,9880656320,nisha.kc217@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Excel, NodeJS, Data Science]",32557,5295,63,51,Morning,2026-08-01,True,False
223,224,Sabina Poudel,25,Male,9816849728,sabina.poudel224@gmail.com,Kathmandu,Kathmandu,Bagmati,[UI/UX],32333,9128,85,95,Weekend,2026-11-18,True,False
228,229,Nabin Poudel,27,Male,9822665814,nabin.poudel229@gmail.com,Kathmandu,Kathmandu,Bagmati,"[UI/UX, Django, Figma, React]",46346,2326,88,98,Evening,2026-02-17,True,False
247,248,Nabin Shrestha,27,Female,9820839642,nabin.shrestha248@gmail.com,Kathmandu,Kathmandu,Bagmati,[C++],44452,5924,66,85,AI Udaan Day,2026-03-12,True,False
254,255,Suman Thapa,30,Female,9843792484,suman.thapa255@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Digital Marketing, Power BI]",17107,9713,87,70,Morning,2026-09-24,True,False
269,270,Bibek Lama,27,Male,9832015139,bibek.lama270@gmail.com,Kathmandu,Kathmandu,Bagmati,[MERN],32911,8446,62,47,AI Udaan Day,2026-06-14,False,False
277,278,Aarav KC,27,Male,9839543025,aarav.kc278@gmail.com,Kathmandu,Kathmandu,Bagmati,"[MERN, Digital Marketing]",27530,5537,87,72,Weekend,2026-02-24,True,False
281,282,Ramesh Lama,26,Male,9806541621,ramesh.lama282@gmail.com,Kathmandu,Kathmandu,Bagmati,[Java],37618,7332,71,45,Weekend,2026-04-15,False,False
283,284,Bibek Khadka,23,Female,9858917470,bibek.khadka284@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Python, Excel, UI/UX, Data Science]",43555,6589,63,84,AI Udaan Day,2026-06-23,True,False
309,310,Gita Adhikari,21,Female,9893386101,gita.adhikari310@gmail.com,Kathmandu,Kathmandu,Bagmati,"[React, Data Science, Excel, NodeJS]",39981,6613,91,48,Weekend,2026-12-12,False,False
311,312,Pooja Gautam,17,Male,9836282673,pooja.gautam312@gmail.com,Kathmandu,Kathmandu,Bagmati,[Data Science],42980,3319,84,64,Weekend,2026-07-13,True,False
314,315,Sita Pandey,20,Female,9824895179,sita.pandey315@gmail.com,Kathmandu,Kathmandu,Bagmati,"[MERN, NodeJS]",31233,7051,74,50,AI Udaan Day,2026-01-12,True,False
318,319,Nabin Pandey,24,Female,9824308867,nabin.pandey319@gmail.com,Kathmandu,Kathmandu,Bagmati,[Flutter],26160,730,60,58,AI Udaan Day,2026-01-25,True,False
341,342,Asmita Regmi,30,Male,9838184915,asmita.regmi342@gmail.com,Kathmandu,Kathmandu,Bagmati,"[AI/ML, Excel, Power BI]",22284,3516,70,58,AI Udaan Day,2026-01-18,True,False
375,376,Alina Bhattarai,26,Female,9853893114,alina.bhattarai376@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Digital Marketing, NodeJS]",17272,2671,66,89,Weekend,2026-11-22,True,False
402,403,Asmita Acharya,28,Female,9824932892,asmita.acharya403@gmail.com,Kathmandu,Kathmandu,Bagmati,[Flutter],45374,5622,80,93,Evening,2026-12-07,True,False
417,418,Bibek Dahal,19,Female,9872756171,bibek.dahal418@gmail.com,Kathmandu,Kathmandu,Bagmati,[C++],19356,3323,74,52,Evening,2026-01-24,True,False
427,428,Prakash Gautam,25,Female,9857534162,prakash.gautam428@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Excel, MERN]",49062,7377,97,94,Weekend,2026-07-24,True,True
443,444,Alina Adhikari,22,Male,9895746608,alina.adhikari444@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Java, MERN, Deep Learning, Flutter]",38045,6742,74,74,Evening,2026-10-21,True,False
444,445,Kiran Magar,23,Female,9840999561,kiran.magar445@gmail.com,Kathmandu,Kathmandu,Bagmati,[Digital Marketing],37246,4944,67,70,Evening,2026-12-22,True,False
473,474,Ritika Pandey,27,Male,9840557150,ritika.pandey474@gmail.com,Kathmandu,Kathmandu,Bagmati,[Python],21704,8946,63,65,Morning,2026-03-05,True,False
477,478,Suman Magar,17,Male,9849257988,suman.magar478@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Django, Deep Learning, Figma, NodeJS]",35022,7068,62,77,AI Udaan Day,2026-11-13,True,False
485,486,Rohan Joshi,25,Female,9809910095,rohan.joshi486@gmail.com,Kathmandu,Kathmandu,Bagmati,[NodeJS],19013,3188,82,65,Weekend,2026-10-26,True,False
493,494,Mina Sharma,25,Female,9857967801,mina.sharma494@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Power BI, React, C++, AI/ML]",35549,8787,64,60,Morning,2026-01-12,True,False

In [42]:
# 16. Display students older than 21
sd[sd['age'] > 21]

,id,name,age,gender,phone,email,location,district,province,courses_enrolled,fees_paid,fees_due,attendance,marks,batch,join_date,passed,scholarship
1,2,Sujan Poudel,28,Male,9870676580,sujan.poudel2@gmail.com,Nepalgunj,Banke,Lumbini,[Flutter],46200,3006,75,78,Evening,2026-12-02,True,False
2,3,Nabin Pandey,26,Male,9834006426,nabin.pandey3@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Django, Deep Learning, Python, React]",37409,3541,94,59,Weekend,2026-08-06,True,False
3,4,Roshan Regmi,27,Female,9811229824,roshan.regmi4@gmail.com,Dharan,Sunsari,Koshi,"[Figma, Python, Flutter, Excel]",47846,1196,90,73,Weekend,2026-10-20,True,False
4,5,Anisha Regmi,25,Male,9824458163,anisha.regmi5@gmail.com,Chitwan,Chitwan,Bagmati,[Data Science],23403,6333,76,62,Evening,2026-12-20,True,False
6,7,Gita Magar,22,Male,9820101977,gita.magar7@gmail.com,Nepalgunj,Banke,Lumbini,"[Deep Learning, NodeJS, Flutter]",21953,2237,91,53,AI Udaan Day,2026-09-02,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,Asmita Rai,27,Female,9836813605,asmita.rai496@gmail.com,Pokhara,Kaski,Gandaki,"[Figma, Power BI, MERN]",36254,4325,89,58,Weekend,2026-05-12,True,False
496,497,Ramesh Joshi,28,Male,9826553259,ramesh.joshi497@gmail.com,Chitwan,Chitwan,Bagmati,"[Power BI, Digital Marketing, MERN]",29738,2434,96,86,Evening,2026-11-06,True,False
497,498,Sabina Khadka,25,Male,9820772678,sabina.khadka498@gmail.com,Janakpur,Dhanusha,Madhesh,"[C++, Digital Marketing, Excel, Power BI]",16298,2316,81,85,Evening,2026-07-15,True,False
498,499,Rohan Acharya,30,Female,9833337211,rohan.acharya499@gmail.com,Chitwan,Chitwan,Bagmati,"[C++, Digital Marketing]",37942,1242,73,65,Evening,2026-01-09,True,False
499,500,Sujan KC,23,Female,9840665873,sujan.kc500@gmail.com,Nepalgunj,Banke,Lumbini,"[Figma, AI/ML]",27145,917,65,98,Morning,2026-12-19,True,False

In [43]:
# 17. Display female students
sd[sd['gender'] == 'Female']

,id,name,age,gender,phone,email,location,district,province,courses_enrolled,fees_paid,fees_due,attendance,marks,batch,join_date,passed,scholarship
3,4,Roshan Regmi,27,Female,9811229824,roshan.regmi4@gmail.com,Dharan,Sunsari,Koshi,"[Figma, Python, Flutter, Excel]",47846,1196,90,73,Weekend,2026-10-20,True,False
5,6,Ramesh Magar,20,Female,9825490998,ramesh.magar6@gmail.com,Dharan,Sunsari,Koshi,"[Django, C++]",40078,7868,73,89,Morning,2026-09-05,True,False
8,9,Alina Joshi,27,Female,9828747392,alina.joshi9@gmail.com,Janakpur,Dhanusha,Madhesh,"[Data Science, UI/UX]",42928,1898,94,84,Evening,2026-05-12,True,False
11,12,Kiran Poudel,25,Female,9803953697,kiran.poudel12@gmail.com,Chitwan,Chitwan,Bagmati,[Java],23324,2540,78,95,Weekend,2026-12-10,True,False
13,14,Roshan Thapa,29,Female,9834257153,roshan.thapa14@gmail.com,Dharan,Sunsari,Koshi,"[AI/ML, Flutter]",39265,8759,95,88,Weekend,2026-10-10,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,494,Mina Sharma,25,Female,9857967801,mina.sharma494@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Power BI, React, C++, AI/ML]",35549,8787,64,60,Morning,2026-01-12,True,False
494,495,Asmita Gautam,21,Female,9803716146,asmita.gautam495@gmail.com,Dharan,Sunsari,Koshi,"[Power BI, UI/UX, Digital Marketing, React]",29023,4987,60,63,Evening,2026-04-27,True,False
495,496,Asmita Rai,27,Female,9836813605,asmita.rai496@gmail.com,Pokhara,Kaski,Gandaki,"[Figma, Power BI, MERN]",36254,4325,89,58,Weekend,2026-05-12,True,False
498,499,Rohan Acharya,30,Female,9833337211,rohan.acharya499@gmail.com,Chitwan,Chitwan,Bagmati,"[C++, Digital Marketing]",37942,1242,73,65,Evening,2026-01-09,True,False
499,500,Sujan KC,23,Female,9840665873,sujan.kc500@gmail.com,Nepalgunj,Banke,Lumbini,"[Figma, AI/ML]",27145,917,65,98,Morning,2026-12-19,True,False

In [44]:
# 18. Display students whose attendance is greater than 90
sd[sd['attendance'] > 90]

,id,name,age,gender,phone,email,location,district,province,courses_enrolled,fees_paid,fees_due,attendance,marks,batch,join_date,passed,scholarship
2,3,Nabin Pandey,26,Male,9834006426,nabin.pandey3@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Django, Deep Learning, Python, React]",37409,3541,94,59,Weekend,2026-08-06,True,False
6,7,Gita Magar,22,Male,9820101977,gita.magar7@gmail.com,Nepalgunj,Banke,Lumbini,"[Deep Learning, NodeJS, Flutter]",21953,2237,91,53,AI Udaan Day,2026-09-02,True,False
8,9,Alina Joshi,27,Female,9828747392,alina.joshi9@gmail.com,Janakpur,Dhanusha,Madhesh,"[Data Science, UI/UX]",42928,1898,94,84,Evening,2026-05-12,True,False
9,10,Sujan Dahal,18,Male,9883749719,sujan.dahal10@gmail.com,Itahari,Sunsari,Koshi,[Deep Learning],40874,2753,95,82,Weekend,2026-03-18,True,False
10,11,Anisha Acharya,22,Male,9899911161,anisha.acharya11@gmail.com,Chitwan,Chitwan,Bagmati,"[AI/ML, Power BI, C++]",42448,2137,92,57,Morning,2026-02-22,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,479,Sita Adhikari,21,Female,9886949442,sita.adhikari479@gmail.com,Itahari,Sunsari,Koshi,"[Django, Digital Marketing, Figma, UI/UX]",32177,6936,91,70,Weekend,2026-09-24,True,False
479,480,Pooja Poudel,23,Male,9842710675,pooja.poudel480@gmail.com,Pokhara,Kaski,Gandaki,"[React, UI/UX]",27391,4034,96,64,Morning,2026-04-27,True,False
488,489,Prakash KC,24,Female,9871798830,prakash.kc489@gmail.com,Itahari,Sunsari,Koshi,"[Flutter, NodeJS, AI/ML]",29418,8585,96,65,Morning,2026-05-16,True,False
490,491,Pooja KC,28,Female,9867136985,pooja.kc491@gmail.com,Dharan,Sunsari,Koshi,[Python],26989,1332,96,65,Weekend,2026-03-26,True,False
496,497,Ramesh Joshi,28,Male,9826553259,ramesh.joshi497@gmail.com,Chitwan,Chitwan,Bagmati,"[Power BI, Digital Marketing, MERN]",29738,2434,96,86,Evening,2026-11-06,True,False

In [45]:
# 19. Display students whose marks are above 85
sd[sd['marks'] > 85]

,id,name,age,gender,phone,email,location,district,province,courses_enrolled,fees_paid,fees_due,attendance,marks,batch,join_date,passed,scholarship
5,6,Ramesh Magar,20,Female,9825490998,ramesh.magar6@gmail.com,Dharan,Sunsari,Koshi,"[Django, C++]",40078,7868,73,89,Morning,2026-09-05,True,False
7,8,Asmita Pandey,21,Male,9812467748,asmita.pandey8@gmail.com,Chitwan,Chitwan,Bagmati,"[UI/UX, React]",29730,9428,86,91,Weekend,2026-03-11,True,False
11,12,Kiran Poudel,25,Female,9803953697,kiran.poudel12@gmail.com,Chitwan,Chitwan,Bagmati,[Java],23324,2540,78,95,Weekend,2026-12-10,True,False
13,14,Roshan Thapa,29,Female,9834257153,roshan.thapa14@gmail.com,Dharan,Sunsari,Koshi,"[AI/ML, Flutter]",39265,8759,95,88,Weekend,2026-10-10,True,False
15,16,Suman Adhikari,26,Female,9874774221,suman.adhikari16@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Digital Marketing, Deep Learning, MERN]",47608,7760,87,88,Evening,2026-12-14,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482,483,Nisha Acharya,24,Male,9881680664,nisha.acharya483@gmail.com,Janakpur,Dhanusha,Madhesh,"[AI/ML, UI/UX]",22904,2898,90,89,AI Udaan Day,2026-12-08,True,False
487,488,Sujan Poudel,30,Female,9885368000,sujan.poudel488@gmail.com,Lalitpur,Lalitpur,Bagmati,"[Django, Power BI]",35143,310,65,97,Weekend,2026-11-15,True,False
491,492,Ritika Poudel,28,Female,9827170264,ritika.poudel492@gmail.com,Janakpur,Dhanusha,Madhesh,"[C++, UI/UX, Deep Learning, Flutter]",23402,5547,68,86,Weekend,2026-05-04,True,False
496,497,Ramesh Joshi,28,Male,9826553259,ramesh.joshi497@gmail.com,Chitwan,Chitwan,Bagmati,"[Power BI, Digital Marketing, MERN]",29738,2434,96,86,Evening,2026-11-06,True,False
499,500,Sujan KC,23,Female,9840665873,sujan.kc500@gmail.com,Nepalgunj,Banke,Lumbini,"[Figma, AI/ML]",27145,917,65,98,Morning,2026-12-19,True,False

In [46]:
# 20. Display students enrolled in Python
sd[sd['courses_enrolled'].apply(lambda x: 'Python' in x)]

,id,name,age,gender,phone,email,location,district,province,courses_enrolled,fees_paid,fees_due,attendance,marks,batch,join_date,passed,scholarship
2,3,Nabin Pandey,26,Male,9834006426,nabin.pandey3@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Django, Deep Learning, Python, React]",37409,3541,94,59,Weekend,2026-08-06,True,False
3,4,Roshan Regmi,27,Female,9811229824,roshan.regmi4@gmail.com,Dharan,Sunsari,Koshi,"[Figma, Python, Flutter, Excel]",47846,1196,90,73,Weekend,2026-10-20,True,False
17,18,Sabina Dahal,19,Female,9888478039,sabina.dahal18@gmail.com,Itahari,Sunsari,Koshi,"[Python, Excel]",34707,7506,65,87,Weekend,2026-10-21,True,False
19,20,Sabina Shrestha,20,Female,9851899869,sabina.shrestha20@gmail.com,Nepalgunj,Banke,Lumbini,[Python],18725,1988,91,83,Morning,2026-08-01,True,False
22,23,Nabin Bhattarai,24,Male,9833072767,nabin.bhattarai23@gmail.com,Chitwan,Chitwan,Bagmati,"[C++, Flutter, Data Science, Python]",19844,4670,69,54,Evening,2026-10-02,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
468,469,Roshan KC,24,Female,9873162845,roshan.kc469@gmail.com,Lalitpur,Lalitpur,Bagmati,"[Django, Python, Power BI, Deep Learning]",20046,8974,98,80,Evening,2026-11-15,True,False
470,471,Asmita Joshi,26,Male,9806889815,asmita.joshi471@gmail.com,Chitwan,Chitwan,Bagmati,"[Python, Data Science, Figma, Java]",42147,3359,61,47,Evening,2026-05-17,False,False
473,474,Ritika Pandey,27,Male,9840557150,ritika.pandey474@gmail.com,Kathmandu,Kathmandu,Bagmati,[Python],21704,8946,63,65,Morning,2026-03-05,True,False
484,485,Alina Bhandari,26,Male,9801096657,alina.bhandari485@gmail.com,Lalitpur,Lalitpur,Bagmati,"[C++, Python, MERN]",39900,3025,79,49,AI Udaan Day,2026-05-18,False,False
490,491,Pooja KC,28,Female,9867136985,pooja.kc491@gmail.com,Dharan,Sunsari,Koshi,[Python],26989,1332,96,65,Weekend,2026-03-26,True,False